const crypto = require("crypto");
const fs = require("fs");
const path = require("path");

function token(bytes = 24) {
  return crypto.randomBytes(bytes).toString("base64url");
}

function argValue(name) {
  const prefix = `${name}=`;
  const direct = process.argv.find((arg) => arg.startsWith(prefix));
  if (direct) return direct.slice(prefix.length);
  const index = process.argv.indexOf(name);
  return index >= 0 ? process.argv[index + 1] : "";
}

function safeOutputPath(filePath) {
  if (!filePath) return "";
  const resolved = path.resolve(process.cwd(), filePath);
  const cwd = process.cwd();
  if (resolved !== path.join(cwd, ".env.local") && resolved !== path.join(cwd, ".env.production.local")) {
    throw new Error("Secret output is limited to .env.local or .env.production.local");
  }
  return resolved;
}

const adminPin = token(18);
const betaCode = `beta-${token(12)}`;
const sessionSecret = token(48);
const outputPath = safeOutputPath(argValue("--write"));
const content = [
  "# Generated by npm run secrets -- --write .env.local",
  "# Keep this file private. Do not commit or paste it into chat.",
  `ADMIN_PIN=${adminPin}`,
  `SESSION_SECRET=${sessionSecret}`,
  `BETA_ACCESS_CODE=${betaCode}`,
  "",
].join("\n");

if (outputPath) {
  if (fs.existsSync(outputPath) && !process.argv.includes("--force")) {
    console.error(`Refusing to overwrite existing ${path.basename(outputPath)}. Add --force if you intentionally want to rotate these values.`);
    process.exit(1);
  }
  fs.writeFileSync(outputPath, content, { mode: 0o600 });
  console.log(`Secret values written to ${path.basename(outputPath)}.`);
  console.log("Keep the file private and paste values only into the hosting dashboard.");
  process.exit(0);
}

console.log("PartyFinder generated secrets");
console.log("");
console.log("Paste these into your hosting provider environment settings:");
console.log("");
console.log(`ADMIN_PIN=${adminPin}`);
console.log(`SESSION_SECRET=${sessionSecret}`);
console.log(`BETA_ACCESS_CODE=${betaCode}`);
console.log("");
console.log("Keep these private. Send BETA_ACCESS_CODE only to invited beta testers.");
